### 직접 JSON 사용
POST localhost:8080/users
Content-Type: application/json

{
  "userName": "노벰버",
  "password": "abc666",
  "email": "n6@gmail.com",
  "id": "user6"
}

###
GET localhost:8080/users

###
GET localhost:8080/test