### 이메일과 비밀번호를 이용한 회원조회(Encrypt 미적용)
GET localhost:8080/users/userInfo?Email=zebra@gmail.com&Pwd=zebra333

### 회원 조회 Email Pwd(Encrypt 적용)
GET localhost:8080/users/userInfo?Email=fox@gmail.com&Pwd=fox777


### 회원번호를 이용한 회원조회
GET localhost:8080/users/2

### 모든 회원 조회
GET http://localhost:8080/users/getAll

### 회원 등록1 (모든 Data Insert)
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "김한나",
  "nickName": "fox",
  "email": "fox@gmail.com",
  "password": "fox777",
  "phone": "010-7777-8888",
  "profileImgUrl": "foxImg",
  "website": "foxdot.com",
  "introduce": "여우같이 앙큼하게"
}

### 회원 등록2 (Null Data exists)
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "서민수",
  "nickName": "gorilla",
  "email": "gorilla@gmail.com",
  "password": "gorilla888",
  "phone": "010-9999-8888"
}

### 회원 삭제(Status=>INACTIVE)
PATCH http://localhost:8080/users/status/delete
Content-Type: application/json

{
  "email": "gorilla@gmail.com",
  "password": "gorilla888"
}

### 회원 복구(Status=>ACTIVE)
PATCH http://localhost:8080/users/status/restore
Content-Type: application/json

{
  "email": "gorilla@gmail.com",
  "password": "gorilla888"
}

### 회원 정보에 따른 포스트 리스트 조회
GET http://localhost:8080/users/feed/13


### 회원 번호에 대하여 작성한 게시물 확인
GET http://localhost:8080/posts?userIdx=12

### 게시물 작성 API
POST http://localhost:8080/posts
Content-Type: application/json

{
  "userIdx": 12,
  "content": "TEST API WORKING",
  "postImgsUrl": ["TestUrl1.img", "TestUrl2.img"]
}

### 게시물 수정 API
PATCH http://localhost:8080/posts/7
Content-Type: application/json

{
  "userIdx": 12,
  "content": "TEST API UPDATED"
}

### 게시물 삭제 API
PATCH http://localhost:8080/posts/7/status